### ISSUE TITLE
Bubble _sort

### ISSUE THREAD

**Issue by manikantanynala97** [Bharanidharan7708/Hacktober2023#12]
hey the algorithm of bubble sort is written wrong and the algorithm is a sorting algorithm which pushes the 1 st minimum number in the 1st iteration and 2nd minimum number in the second iteration and it will be sorted but bubble sort is different and can u respond whether my answer is correct and can I solve this issue .

**Comment by kartikeysharma98281** [comment]
hey @manikantanynala97 can you assign this issue to me

**Comment by manikantanynala97** [comment]
@kartikeysharma98281  yes u can

**Comment by coderavneet** [comment]
can you assign the issue to me?

**Comment by Bharanidharan7708** [comment]
@coderavneet yes

**Comment by punitsakre23** [comment]
Hi @Bharanidharan7708 Can I work on this in java.
If yes, plz assign it to me.
Thanks 😀

**Comment by Palash-05** [comment]
Hi @Bharanidharan7708, I see the latest commit solves the objective in Theta(n^2). which is obviously not the best time complexity for bubble sort. Can I work on this and provide the most optimized approach.
If yes, please assign it to me. Thanks.

**Comment by Bharanidharan7708** [comment]
@Palash-05 okay work on it

**Comment by TanishqRinjay** [comment]
Is it open now?
Can I contribute?

**Comment by Bharanidharan7708** [comment]
Yes ,you can!

**Comment by Parth-Sharma-tonchi** [comment]
@Bharanidharan7708, Hey this algorithm takes 50 inputs and provides a sorting array of only n numbers. I can fix this issue. Can you assign this to me to contribute?
