### ISSUE TITLE
Linked List 

### ISSUE THREAD

**Issue by shikha72** [Bharanidharan7708/Hacktober2023#33]

**Comment by DarathiJeyaraj** [comment]
@Bharanidharan7708  hii can I work on this ?will assign ?

**Comment by Bharanidharan7708** [comment]
@DarathiJeyaraj sure

**Comment by DarathiJeyaraj** [comment]
can i do it in C?

**Comment by Bharanidharan7708** [comment]
@DarathiJeyaraj Yes you can.

**Comment by soumyo2002** [comment]
hey @Bharanidharan7708, can I work on this task in C++?

**Comment by manishtambe** [comment]
hi @Bharanidharan7708  I want to implement a doubly circular & singly circular list please assign me this issue

**Comment by Bharanidharan7708** [comment]
Done > hi @Bharanidharan7708  I want to implement a doubly circular & singly circular list please assign me this issue

**Comment by manishtambe** [comment]
Hi @Bharanidharan7708 I have sent a PR #33 , please check and merge it. Thank you!

**Comment by Bharanidharan7708** [comment]
Closing issue
